"""
Page 3 — Investigations browser.

Lists all agent-generated investigation briefs from Postgres. Each row
expands to show the full markdown report. Includes ticker filter and
pagination.

This is *the* showcase page for the agent's work — when a recruiter clicks
into the dashboard during your demo, this is where you click first.
"""

import streamlit as st
from streamlit_autorefresh import st_autorefresh

from lib.data import get_investigations, TICKERS


st.set_page_config(
    page_title="PulseTrade — Investigations",
    page_icon="🔍",
    layout="wide",
)

# Slower refresh — investigations don't change every 30s, and we don't want
# to interrupt someone mid-read of a long report
st_autorefresh(interval=60_000, key="investigations_refresh")


# ── Sidebar ─────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("PulseTrade")
    st.divider()
    st.subheader("Filters")

    ticker_filter = st.multiselect(
        "Tickers",
        options=TICKERS,
        default=TICKERS,
        help="Filter investigations to specific tickers",
    )

    page_size = st.select_slider(
        "Per page",
        options=[5, 10, 25, 50],
        value=10,
    )

    st.divider()
    st.caption("Auto-refresh: every 60s")


# ── Main ────────────────────────────────────────────────────────────────────
st.title("🔍 Investigations")
st.caption(
    "Markdown briefs generated by the LangGraph + MCP agent in response to "
    "anomaly alerts. Click any row to read the full report."
)

result = get_investigations(limit=200)

if result.is_synthetic:
    st.warning(
        f"⚠️ Investigations DB unavailable — showing synthetic. Error: `{result.error}`"
    )

if result.df.empty:
    st.info("No investigations yet. Trigger one from the **Trigger** page.")
else:
    df = result.df.copy()

    # Filter by selected tickers
    if ticker_filter:
        df = df[df["ticker"].isin(ticker_filter)]

    if df.empty:
        st.info("No investigations match the selected filters.")
    else:
        # Make timestamps tz-aware-pretty
        df["created_at"] = (
            df["created_at"]
            .astype("datetime64[ns, UTC]")
            .dt.strftime("%Y-%m-%d %H:%M UTC")
        )

        # Pagination via session state
        if "inv_page" not in st.session_state:
            st.session_state.inv_page = 0

        total = len(df)
        max_page = max(0, (total - 1) // page_size)

        # Clip page index if filters reduced total
        if st.session_state.inv_page > max_page:
            st.session_state.inv_page = max_page

        page = st.session_state.inv_page
        start = page * page_size
        end = min(start + page_size, total)
        page_df = df.iloc[start:end]

        # ── Header row: result count + pagination controls ─────────────────
        c1, c2, c3, c4 = st.columns([3, 1, 1, 1])
        with c1:
            st.markdown(
                f"**Showing {start+1}–{end} of {total}** investigations"
            )
        with c2:
            if st.button("⬅️ Prev", disabled=(page == 0), use_container_width=True):
                st.session_state.inv_page = max(0, page - 1)
                st.rerun()
        with c3:
            st.markdown(
                f"<div style='text-align:center;padding-top:8px;'>"
                f"Page {page+1} / {max_page+1}</div>",
                unsafe_allow_html=True,
            )
        with c4:
            if st.button("Next ➡️", disabled=(page >= max_page), use_container_width=True):
                st.session_state.inv_page = min(max_page, page + 1)
                st.rerun()

        st.divider()

        # ── List of investigations, each expandable ────────────────────────
        for _, row in page_df.iterrows():
            header = (
                f"**{row['ticker']}**  ·  {row['anomaly_type']}  ·  "
                f"{row['created_at']}  ·  ID {row['id']}"
            )
            with st.expander(header, expanded=False):
                # Quick metadata row
                meta_cols = st.columns(3)
                with meta_cols[0]:
                    st.caption("Ticker")
                    st.markdown(f"**{row['ticker']}**")
                with meta_cols[1]:
                    st.caption("Anomaly type")
                    st.markdown(f"**{row['anomaly_type']}**")
                with meta_cols[2]:
                    st.caption("Window start")
                    ws = row.get("window_start")
                    st.markdown(f"**{ws}**" if ws else "—")

                st.divider()

                # The markdown brief — Streamlit renders it natively
                report = row.get("report_markdown") or "_(no report)_"
                st.markdown(report)